export * from "./common.interface";
export * from "./admin.interface";
export * from "./accountUser.interface";
export * from './accountRole.interface';
export * from './accountUserRole.interface'
export * from './adminRegion.interface'
export * from './region.interface';
export * from './role.interface';
export * from './requestStatusLog.interface'
export * from './request.interface'
export * from './physician.interface'
export * from './user.interface'