export * from "./common.interface";
export * from './account.interface'
export * from "./admin.interface";
export * from './region.interface';
export * from './role.interface';
export * from './request.interface'
export * from './physician.interface'
export * from './user.interface'
export * from './requestType.interface'